# -*- coding: utf-8 -*-
"""PharmacySystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ybLCGUgM6Td7XqUiccliaEIARWBpPQjZ
"""

! pip install experta
! pip uninstall daal==2021.5.0
! pip install daal==2021.4.0
! pip uninstall numpy==1.18.5
! pip install numpy==1.8.2
! pip install numpy==1.21.5
! pip uninstall requests==2.18.4
! pip install requests==2.25.1

! pip install experta

!pip install --upgrade frozendict

from experta import*

class pharmcy_vending_machine(Fact):
  pass
class choose_your_symptom(KnowledgeEngine):

  #*************================One Symptom Selected================*************

  #==========================Fever degrees by age========================
  #--------------------------Fever Age1 degree less than 38-----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age = ('Y'))))
  def Fever_age_lessThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is: \nAcetaminophen.\nTOTAL: 13.15SR")
  #--------------------------Fever Age1 degree more than than 38-----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('Y')),pharmcy_vending_machine(age = ('Y'))))
  def Fever_age_moreThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is: \nIbuprofen.\nTOTAL: 27.55SR")
  #--------------------------Fever Age2 degree less than than 38----------------------- 
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age2 = ('Y'))))
  def Fever_age2_lessThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is: \nTylenol.\nTOTAL: 12.95SR")
  #--------------------------Fever Age2 degree more than than 38-----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('Y')),pharmcy_vending_machine(age2 = ('Y'))))
  def Fever_age2_moreThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is: \nAdvil.\nTOTAL: 11.75SR")
  #--------------------------Fever Age3 degree less than than 38-----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age3 = ('Y'))))
  def Fever_age3_lessThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is: \nTylenol.\nTOTAL: 12.95SR")
  #--------------------------Fever Age3 degree more than than 38-----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('Y')),pharmcy_vending_machine(age3 = ('Y'))))
  def Fever_age3_moreThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is: \nAspirin.\nTOTAL: 19.05SR")
  #--------------------------Nasal Age1 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('N')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age = ('Y'))))
  def Nasal(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is: \nSinomarin Nasal Spray Children 100ml.\nTOTAL: 54.0SR")
  #--------------------------Nasal Age2 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('N')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age2 = ('Y'))))
  def Nasal2(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is: \nOtrivin 0.05% children nasal drop 1-2 drops in each nostril 1-2 times a day.\nTOTAL: 13.8SR")
  #--------------------------Nasal Age3 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('N')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age3 = ('Y'))))
  def Nasal3(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene are: \nClarinase Repetabs (one tablet twice daily)\nOtrivin Nasal Spray 10ml.\nTOTAL: 31.0SR")
  #--------------------------Sore Throat Age1 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('N')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age = ('Y'))))
  def sore_throat(Self):
    print("\n-----------------------------------------------------\nAdol 120 mg/5ml Syrup 100 ml.\nTOTAL: 5.80 SR")
  #--------------------------Sore Throat Age2 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('N')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age2 = ('Y'))))
  def sore_throat2(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is: \nMedex Propolis Oral Water-Based Spray 30 Ml.\nTOTAL: 69.35SR")
  #--------------------------Sore Throat Age3 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('N')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age3 = ('Y'))))
  def sore_throat3(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are: \nClarinase Repetabs, one tablet twice daily.\nStrepsils Lozenge 24pcs Honey & Lemon.\nTOTAL: 34.0SR")
  #--------------------------Headache pain1 -----------------------
  @Rule(AND(pharmcy_vending_machine(Headaches1= ('Y')),pharmcy_vending_machine(pain1 = ('Y'))))
  def headache1(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is: \nSumarex is given to the patient.\nTOTAL: 30.20SR")
  #--------------------------Headache pain2 -----------------------
  @Rule(AND(pharmcy_vending_machine(Headaches1= ('Y')),pharmcy_vending_machine(pain1 = ('N')),
            pharmcy_vending_machine(pain2 = ('Y'))))
  def headache2(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is: \nAspirin is given to the patient.\nTOTAL: 8.15SR")
  #--------------------------Headache pain3 -----------------------
  @Rule(AND(pharmcy_vending_machine(Headaches1= ('Y')),pharmcy_vending_machine(pain1 = ('N')),
            pharmcy_vending_machine(pain2 = ('N')),pharmcy_vending_machine(pain3 = ('Y'))))
  def headache3(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is:\nIbuprofen is given to the patient.\nTOTAL: 27.55SR")


  #*************================Two Symptom Selected================*************

  #++++++++++++++++++++++++++++++++Fever Nasal_congestion++++++++++++++++++++++++++++++++++ 
  #First Age
  #--------------------------Fever Nasal_congestion less than than 38 Age1 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age = ('Y'))))
  def Fever_nasal1_lessThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nAcetaminophen is given to the patient.\nSinomarin Nasal Spray Children 100ml.\nTOTAL: 81.55SR")

  #--------------------------Fever Nasal_congestion more than than 38 Age1 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('Y')),pharmcy_vending_machine(age = ('Y'))))
  def Fever_nasal1_moreThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nIbuprofenis given to the patient.\nSinomarin Nasal Spray Children 100ml.\nTOTAL: 67.15SR")
  #Second Age
  #--------------------------Fever Nasal_congestion less than than 38 Age2 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age2 = ('Y'))))
  def Fever_nasal2_lessThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nTylenol is given to the patient.\nOtrivin 0.05% children nasal drop, 1-2 drops in each nostril 1-2 times a day.\nTOTAL: 25.75SR")

  #--------------------------Fever Nasal_congestion more than than 38 Age2 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('Y')),pharmcy_vending_machine(age2 = ('Y'))))
  def Fever_nasal2_moreThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nAdvil is given to the patient.\nOtrivin 0.05% children nasal drop, 1-2 drops in each nostril 1-2 times a day.\nTOTAL: 25.55SR")
  #Third Age
  #--------------------------Fever Nasal_congestion less than than 38 Age3 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age3 = ('Y'))))
  def Fever_nasal3_lessThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene are:\nTylenol is given to the patient.\nClarinase Repetabs (one tablet twice daily).\nOtrivin Nasal Spray 10ml.\nTOTAL: 25.20SR")

  #--------------------------Fever Nasal_congestion more than than 38 Age3 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('N')),
            pharmcy_vending_machine(degrees1 = ('Y')),pharmcy_vending_machine(age3 = ('Y'))))
  def Fever_nasal3_moreThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene are:\nAspirin is given to the patient.\nClarinase Repetabs (one tablet twice daily).\nOtrivin Nasal Spray 10ml.\nTOTAL: 21.95SR")

  
  #++++++++++++++++++++++++++++++++Fever Sore_throat++++++++++++++++++++++++++++++++++
  
  #First Age
  #--------------------------Fever Sore_throat less than 38 Age1 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age = ('Y'))))
  def Fever_Sore_throat_less(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is:\nAcetaminophen is given to the patient.\nTOTAL: 38.15SR")

  #--------------------------Fever Sore_throat more than 38 Age1 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('Y')),pharmcy_vending_machine(age = ('Y'))))
  def Fever_Sore_throat_more(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is:\nIbuprofenis is given to the patient.\nTOTAL: 13.60SR")
  #Second Age
  #--------------------------Fever Sore_throat less than 38 Age2 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age2 = ('Y'))))
  def Fever_Sore_throat2_less(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nTylenol is given to the patient. \nMedex Propolis Oral Water-Based Spray 30 Ml.\nTOTAL: 80.75SR")

  #--------------------------Fever Sore_throat more than 38 Age2 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('Y')),pharmcy_vending_machine(age2 = ('Y'))))
  def Fever_Sore_throat2_more(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nAdvil is given to the patient.\nMedex Propolis Oral Water-Based Spray 30 Ml.\nTOTAL: 81.1SR")
  #Third Age
  #--------------------------Fever Sore_throat less than 38 Age3 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age3 = ('Y'))))
  def Fever_Sore_throat3_less(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nTylenol is given to the patient.\nClarinase Repetabs, one tablet twice daily.\nStrepsils Lozenge 24pcs Honey & Lemon.\nTOTAL: 45.4SR")

  #--------------------------Fever Sore_throat more than 38 Age3 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('N')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('Y')),pharmcy_vending_machine(age3 = ('Y'))))
  def Fever_Sore_throat3_more(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nAspirin is given to the patient.\nClarinase Repetabs, one tablet twice daily.\nStrepsils Lozenge 24pcs Honey & Lemon.\nTOTAL: 42.15SR")


  #++++++++++++++++++++++++++++++++Nasal_congestion Sore_throat++++++++++++++++++++++++++++++++++
  #First Age
  #--------------------------Nasal_congestion Sore_throat Age1 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('N')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age = ('Y'))))
  def Nasal_congestionSore_throat1(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene is:\nSinomarin Nasal Spray Children 100ml.\nTOTAL: 54.00SAR")
  #Second Age
  #--------------------------Nasal_congestion Sore_throat Age2 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('N')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age2 = ('Y'))))
  def Nasal_congestionSore_throat2(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nOtrivin 0.05% children nasal drop, 1-2 drops in each nostril 1-2 times a day.\nMedex Propolis Oral Water-Based Spray 30 Ml.\nTOTAL: 83.15SR")
  #Third Age
  #--------------------------Nasal_congestion Sore_throat Age3 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('N')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age3 = ('Y'))))
  def Nasal_congestionSore_throat3(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nXylomet 0.05% Nasal Drop 15 ml children 1-2 drops into each nostril once or twice daily\nClarinase Repetabs, one tablet twice daily.\nStrepsils Lozenge 24pcs Honey & Lemon.\nTOTAL: 60.2SR")



  #*************================Three Symptom Selected================************* 
  #++++++++++++++++++++++++++++++++Fever Nasal_congestion++++++++++++++++++++++++++++++++++ 
  #First Age
  #--------------------------Fever Nasal_congestion Sore_throat less than than 38 Age1 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age = ('Y'))))
  def Fever_nasal_Sore_lessThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicene are:\nAcetaminophen\nSinomarin Nasal Spray Children 100ml\nTOTAL: 81.55SِR")

  #--------------------------Fever Nasal_congestion Sore_throat more than than 38 Age1 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('Y')),pharmcy_vending_machine(age = ('Y'))))
  def Fever_nasal_Sore_moreThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nIbuprofenis.\nSinomarin Nasal Spray Children 100ml.\nTOTAL: 62.4SAR")
  #Second Age
  #--------------------------Fever Nasal_congestion Sore_throat less than than 38 Age2 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age2 = ('Y'))))
  def Fever_nasal_Sore2_lessThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nTylenol.\nOtrivin 0.05% children nasal drop, 1-2 drops in each nostril 1-2 times a day."
    "\nMedex Propolis Oral Water-Based Spray 30 Ml.\nTOTAL: 89.15SAR")

  #--------------------------Fever Nasal_congestion Sore_throatn more than than 38 Age2 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('Y')),pharmcy_vending_machine(age2 = ('Y'))))
  def Fever_nasal_Sore2_moreThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nAdvil.\nOtrivin 0.05% children nasal drop, 1-2 drops in each nostril 1-2 times a day."
    "\nMedex Propolis Oral Water-Based Spray 30 Ml.\nTOTAL: 84.9SAR")
  #Third Age
  #--------------------------Fever Nasal_congestion Sore_throat less than than 38 Age3 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('N')),pharmcy_vending_machine(age3 = ('Y'))))
  def Fever_nasal_Sore3_lessThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nTylenol.\nClarinase Repetabs (one tablet twice daily)\nOtrivin Nasal Spray 10ml."
    "\nOStrepsils Lozenge 24pcs Honey & Lemon.\nTOTAL: 76.40SAR")

  #--------------------------Fever Nasal_congestion more than than 38 Age3 -----------------------
  @Rule(AND(pharmcy_vending_machine(Fever = ('Y')),pharmcy_vending_machine(Nasal_congestion1= ('Y')),pharmcy_vending_machine(sore_throat1= ('Y')),
            pharmcy_vending_machine(degrees1 = ('Y')),pharmcy_vending_machine(age3 = ('Y'))))
  def Fever_nasal_Sore3_moreThan38(Self):
    print("\n-----------------------------------------------------\nThe suitable medicenes are:\nAspirin.\nClarinase Repetabs (one tablet twice daily)." 
    "\nOtrivin Nasal Spray 10ml.\nOStrepsils Lozenge 24pcs Honey & Lemon.\nTOTAL: 84.05SAR")
  

print("-----------------------------------------------------")
print("----------------Welcome To Our Pharmacy--------------")
print("-----------------------------------------------------")

start = input("Do you have flu symptoms (Y/N)? ")
if (start == 'Y'):
  engine = choose_your_symptom()
  engine.reset()

  Fever1 = input("\n> Do you have fever (Y/N)? ")
  Nasal_congestion = input("\n> Do you have nasal congestion (Y/N)? ")
  sore_throat= input("\n> Do you have sore throat (Y/N)? ")
  degrees= input("\n> your degrees more than 38 (Y/N)? ")
  Fage = input ("\n> Are the patient between 6 and 24 months (Y/N)? ")
  if (Fage == 'Y'):
      engine.declare(pharmcy_vending_machine(Fever = Fever1, Nasal_congestion1 = Nasal_congestion, sore_throat1=sore_throat,degrees1=degrees,age = Fage))
      engine.run()
  elif (Fage == 'N'):
    Sage = input ("\n> Are the patient between 2 and 12 years (Y/N)? ")
    if (Sage == 'Y'):
      engine.declare(pharmcy_vending_machine(Fever = Fever1, Nasal_congestion1 = Nasal_congestion, sore_throat1=sore_throat,degrees1=degrees,age2 = Sage))
      engine.run()
    elif (Sage == 'N'):
      Tage = input ("\n> Are the patient above 12 (Y/N)? ")
      if (Tage == 'Y'):
       engine.declare(pharmcy_vending_machine(Fever = Fever1, Nasal_congestion1 = Nasal_congestion,sore_throat1=sore_throat,degrees1=degrees, age3 = Tage))
       engine.run()
elif(start=='N'):
  engine = choose_your_symptom()
  engine.reset()
  Headaches= input("\n> Do you have Headache (Y/N)? ")
  if (Headaches=='Y'):
      painO=input("\n> Headache pain on one side of the head, which leads to a runny nose on the affected side.(Y/N)? ")
      if(painO == 'Y'):
        engine.declare(pharmcy_vending_machine(Headaches1=Headaches,pain1=painO))
        engine.run()
      elif(painO == 'N'):
        painTwo=input("\n> Headache Feeling a throbbing pain on one side of the head.(Y/N)? ")
        if (painTwo == 'Y'):
          engine.declare(pharmcy_vending_machine(Headaches1=Headaches,pain1=painO,pain2=painTwo))
          engine.run()
        elif (painTwo == 'N'):
           painThree=input("\n> Headache begins at the front of the head or the "
              "area around the eyes and then spreads throughout.(Y/N)? ")
           if (painThree == 'Y'):
             engine.declare(pharmcy_vending_machine(Headaches1=Headaches,pain1=painO,pain2=painTwo,pain3=painThree))
             engine.run()
  elif (Headaches=='N'):
    print("\nSORRY WE CAN'T HELP YOU!")

else:
  print("\nWRONG INPUT, TRY AGAIN!")

print("Thanks for using our machine")